### PR TITLE
Add PHP 8 support

### LINKED ISSUE #7: PHP 8 Support
Hello,

Do you have any plans to support PHP 8?  Would you accept a PR that adds support?

### PR DESCRIPTION
**Pull request by magikid**
To support PHP 8, this commit updates the versions support in
composer.json so that it matches all versions newer than PHP 7.  It also
adds PHP 8 to the list of versions that travis runs.

Closes #7

### CODE REVIEW

**Comment by lukewaite** [comment]
Thanks for this will try to get it merged and tagged this evening

**Comment by magikid** [comment]
Is there anything else I can do to help with this?

**Comment by klaussilveira** [comment]
@lukewaite any updates on this? :smile:

**Comment by fernandocarletti** [comment]
@lukewaite hey, can you take a look at it, please. I have this as the only blocker for upgrading the pho version in a project.

**Comment by juniorb2ss** [comment]
@lukewaite Hey man! Do you have a chance to take a look at this?

**Comment by tamara-dietz** [comment]
@lukewaite Any news on when this can be merged? Thank you and @magikid for this 😄

**Comment by lukewaite** [comment]
Released under [v2.2.0](https://github.com/lukewaite/ringphp-guzzle-handler/releases/tag/v2.2.0). Thanks @magikid

**Comment by lukewaite** [comment]
@magikid Heads up, I may have tagged prematurely. The build had failed on 8 - which I fixed after tagging. https://travis-ci.org/github/lukewaite/ringphp-guzzle-handler/jobs/768129485

Not sure if these are just test failures that won't impact for real or not.

**Comment by lukewaite** [comment]
Looks as though it only fails on the `--prefer-lowest` build so likely something else is not tagged properly with regards to min/max versions. Will probably not be an issue for most folks.

**Pull request merged**
