### PR TITLE
Handle async calls

### PR DESCRIPTION
**Pull request by jderusse**
This PR allows application to call Elasticsearch client in an async way.

### CODE REVIEW

**Comment by jderusse** [comment]
@lukewaite I can rebase the PR if you want

**Comment by lukewaite** [comment]
@jderusse Just to make sure I'm clear on this, since it's been a while, this _does_ change the returned value to be a promise rather than a completed request, but RingPHP supports that, since you're returning the RingPHP FutureArray object?

Overall no noticeable difference to consumers, ie the ES client?

**Comment by lukewaite** [comment]
> @lukewaite I can rebase the PR if you want

Certainly, @jderusse -- a rebase is my preference, if you want to discard my merge commit, that would be ideal.

**Comment by jderusse** [comment]
The returned typehint did not changed, it'is still an `FutureArrayInterface` (what's expected by ES client)

The previous implementation returned an already resolved promise: `CompletedFutureArray` (that's require Guzzle call to be synchronous).
My PR return a Promise that may not been resolved yet `FutureArray`.

Elastic search, take care of it by waiting the end of the promise when the client is used in `sync` mode. See https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Transport.php#L140-L153

**Comment by lukewaite** [comment]
Perfect, thank you! 

Will wait on CI, then merge and tag.

**Comment by lukewaite** [comment]
Tagged v2.1.0. Thanks again!

**Pull request merged**
